apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: default
  labels:
    app: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
